Switched the project to C++
kotachang/soundinator pull request #1
Opened 2024-11-04 08:37 UTC by kotachang

### Description
Switched the project language to C++. Functionality should remain the same to the user (phone or python script)

### Changes in the codebase
CMakeLists.txt modified to accomodate changes to the files
soundinator_main.c -> soundinator_main.cpp
nimble/ble functions inside soundinator_main.c -> restructured as the Nimbler class in nimbler.cpp and nimbler.hpp
code sequence (flow of function calls) remains the same

### Testing instructions
1. Build and flash from the original branch
2. Run the python_client.py script as the following: `python python_client.py --name Soundinator face` (this specifies the device name as Soundinator, and face is the hex representation of the characteristic uuid we want to get notified from)
3. Take note of the output from the script
4. Build and flash from this branch (with the C++ code)
5. Repeat steps 2-3 and check that the output is identical to the main branch

2024-11-05 05:23 UTC, dvirhilu commented on ESP32/main/src/soundinator_main.c
goodbye old friend

2024-11-05 05:59 UTC, dvirhilu requested changes

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/soundinator_main.cpp
> +#include "nimble/nimble_port.h"
Are all of the nimble includes required for the main fail? If possible would be better to only include them inside nimbler.hpp for better encapsulation.

Maybe to clarify a little bit, I just meant that we should only "#include" libraries if the code in the file uses them (if they are used by downstream code, they should be included in the downstream file).

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/soundinator_main.cpp
> +// tag for logs
fix comment to follow standard

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/soundinator_main.cpp
> +* Follow programming sequence from https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/bluetooth/nimble/index.html
update this comment - since changing the format to c++ it now diverges from the example. The citation link is probably better in Nimbler.cpp and then update the comment to just describe what this function is doing.

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/inc/nimbler.hpp
> +#define service_uuid_val        (0xBEEF)
allergic reaction

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/inc/nimbler.hpp
> +        const char* device_name;
might be better off as a private member with a getter function to guarantee immutability. Need to look into exact const char * semantics to check whether this is immutable as is.

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/inc/nimbler.hpp
> +        static constexpr char* tag = "Nimbler"; // tag used for logs
Again, might be better as a private member or as a macro

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/inc/nimbler.hpp
> +        static constexpr char* tag = "Nimbler"; // tag used for logs
also look into why constexpr vs const

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +/* gatt service structure definition */
capitalization

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +/* gatt characteristic structure definition */
capitalization

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +/* uuids for main ble service and characteristics */
capitalization

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +    ble_addr_type = 0; // Determines the best address type automatically
uncapitalize inline comment

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +    ble_hs_cfg.sync_cb = _ble_app_on_sync;   // Initialize advertisement only after the host & controller are synced
inline comment uncapitalize

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +    nimble_port_run(); // This function will return only when nimble_port_stop() is executed
uncapitalize inline comment

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +    ble_hs_id_infer_auto(0, &ble_addr_type); // Determines the best address type automatically
inline comment uncapitalize

2024-11-05 05:59 UTC, dvirhilu commented on ESP32/main/src/nimbler.cpp
> +    device_name = ble_svc_gap_device_name(); // Read the BLE device name
uncapitalize

2024-11-05 06:40 UTC, dvirhilu approved these changes
looks goo!

2024-11-05 23:44 UTC, jackysioo commented on ESP32/main/inc/nimbler.hpp
> +#define device_write_val        (0xFACE)
rename `device_write_val` to `device_write_uuid_val` for consistency

2024-11-06 01:00 UTC, jackysioo commented on ESP32/main/inc/nimbler.hpp
> +        static int _device_read(uint16_t con_handle, uint16_t attr_handle, struct ble_gatt_access_ctxt *ctxt, void *arg);
rename `con_handle` to `conn_handle` in `_device_read`

2024-11-06 01:01 UTC, kotachang commented on ESP32/main/inc/nimbler.hpp
> +        static int _device_read(uint16_t con_handle, uint16_t attr_handle, struct ble_gatt_access_ctxt *ctxt, void *arg);
conn_handle is specific to the BLE connection and not a connection to a specific attribute (ex. device_read)

2024-11-06 06:22 UTC, jackysioo commented
Looks good!
![soundinator_c](https://github.com/user-attachments/assets/f3e9fa20-865f-41b0-bfac-c2d3502e57b8)
![soundinator_cpp](https://github.com/user-attachments/assets/a3377355-a89d-4977-964c-5ac19032d8b3)

2024-11-06 06:22 UTC, merged